import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <nav>
          <Image src="" alt="" />
          <a href="/"> Home</a>
          <a href="/events"> Events</a>
          <a href="/about-us"> About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        <a href="">
          <Image src="" alt="" />
          <h2> Events in London</h2>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed 
              ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
              reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
              deserunt mollit anim id est laborum.
          </p>
        </a>

        <a href="">
          <Image src="" alt="" />
          <h2> Events in Barcelona</h2>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed 
              ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
              reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
              deserunt mollit anim id est laborum.
          </p>
        </a>

        <a href="">
          <Image src="" alt="" />
          <h2> Events in San Francisco</h2>
          <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed 
              ut aliquip ex ea commodo consequat. Duis aute irure dolor in 
              reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia
              deserunt mollit anim id est laborum.
          </p>
        </a>
      </main>

      <footer className={styles.footer}>
       
      </footer>
    </div>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  console.log(events_categories);

  return {
      props: {
          data: events_categories,
      },
  };
}